### ISSUE TITLE
ReadAgentStatusFromConfig must be set to "true", "True" does not work

### ISSUE THREAD

**Issue by LukasGibb** [loadbalancer-org/go-feedback-agent#3]
It appears that the ReadAgentStatusFromConfig option is not working if you set the value to "True" (with a capital T) as opposed to "true" (with a lower case t). The example config has the initial value set to "False" (with a capital F) so I just altered that and was disappointing that it wasn't working properly. Then I checked the code and realised why.

I'm not sure of the syntax but I assume the below line in config.go should do a ToLower before comparing the value:

if GlobalConfig.ReadAgentStatusFromConfig.Value == "true"

**Comment by andrew-loadbalancer** [comment]
@LukasGibb Thank you for bringing this to our attention. I will see to that this is fixed and updated in our repository.

**Comment by LukasGibb** [comment]
Fixed in my latest pull request in commit:
https://github.com/LukasGibb/go-feedback-agent/commit/f0908ca065921b92ddb6499071758b7328ab138e
