### ISSUE TITLE
Performance Problems

### ISSUE THREAD

**Issue by LukasGibb** [loadbalancer-org/go-feedback-agent#4]
I have a few performance concerns.

As per the attached screenshot of my task manager, running one check via telnet causes an 80% CPU spike that lasts for about 15 seconds. Running two checks (ie 'telnet localhost 3333' in two separate powershell windows) causes a CPU spike of almost 100% for about 25 seconds.

I'm glad I did some testing before I put this on a live web server with multiple HAProxy backends pointing at it.

Am I doing something wrong? Surely it shouldn't take 100% of your CPU to check how much CPU is currently being used...

Also I have noticed that the checks start out really snappy returning in a matter of milliseconds but then after running the service for a while it starts to degrade and takes 15-25 seconds (as per the example above). This was something that happened with the old LBCPUMon exe and is part of the reason I decided to investigate the new Go one.

Config:
```
<xml>
  <Cpu>
    <ImportanceFactor value="1" />
    <ThresholdValue value="100" />
  </Cpu>
  <Ram>
    <ImportanceFactor value="0" />
    <ThresholdValue value="100" />
  </Ram>
  <TCPService>
    <Name value="HTTP" />
    <IPAddress value="*" />
    <Port value="80" />
    <MaxConnections value="0" />
    <ImportanceFactor value="0" />
  </TCPService>
  <ReadAgentStatusFromConfig value="true" />
  <ReadAgentStatusFromConfigInterval value="5" />
  <AgentStatus value="Normal" />
  <Interval value="60" />
  <Port value="3333" />
</xml>
```

![go-feedback-agent-TaskManager](https://user-images.githubusercontent.com/20919949/54897807-fedc3100-4f1d-11e9-859b-980daf1a1b6a.png)

**Comment by andrew-loadbalancer** [comment]
We are currently looking into this issue. I will keep you posted thanks.

**Comment by andrew-loadbalancer** [comment]
@LukasGibb Are you able to pop me an email at andrew @ loadbalancer.org? This way I can include you with our support team.

**Comment by LukasGibb** [comment]
I have been unable to replicate this again on the machine that originally was exhibiting the behaviour. It has not even been rebooted since I saw it happening so I'm not sure what fixed it. The only thing I know changes is that I installed the .Net version. Now the CPU seems fine when running the .Net or Go versions. Feel free to close this one.
